
#Tweak loot spawning and delays
[loot]
	#Defines if loot can be respawned (applies to all loots)
	lootEnabled = true
	#Defines if Civilian Loot can be respawned
	civilianLootEnabled = true
	#Defines if Civilian Rare Loot can be respawned
	rareCivilianLootEnabled = true
	#Defines if Medical Loot can be respawned
	medicalLootEnabled = true
	#Defines if Police Loot can be respawned
	policeLootEnabled = true
	#Defines if Military Loot can be respawned
	militaryLootEnabled = true
	#Range: > 0
	civilianLootRefreshDelayTicks = 1000
	#Range: > 0
	rareCivilianLootRefreshDelayTicks = 1000
	#Range: > 0
	medicalLootRefreshDelayTicks = 1000
	#Range: > 0
	policeLootRefreshDelayTicks = 1000
	#Range: > 0
	militaryLootRefreshDelayTicks = 1000

#Change every aspect of all zombies
#WARNING: Most changes only affects newly spawned zombies. Previously spawned zombies will retain their old settings.
[zombies]
	#Defines how much health the zombie has (2 health points = 1 heart)
	#Range: 1.0 ~ 1024.0
	advancedZombieMaxHealth = 20.0
	#Defines how much health the zombie has (2 health points = 1 heart)
	#Range: 1.0 ~ 1024.0
	tankZombieMaxHealth = 100.0
	#Defines how much health the zombie has (2 health points = 1 heart)
	#Range: 1.0 ~ 1024.0
	fastZombieMaxHealth = 10.0
	#Defines how much health the zombie has (2 health points = 1 heart)
	#Range: 1.0 ~ 1024.0
	weakZombieMaxHealth = 5.0
	#Defines how much health the zombie has (2 health points = 1 heart)
	#Range: 1.0 ~ 1024.0
	policeZombieMaxHealth = 20.0
	#Defines how much health the zombie has (2 health points = 1 heart)
	#Range: 1.0 ~ 1024.0
	doctorZombieMaxHealth = 20.0
	#Defines how much health the zombie has (2 health points = 1 heart)
	#Range: 1.0 ~ 1024.0
	giantZombieMaxHealth = 100.0
	#Defines how much damage the zombie deals (2 damage points points = 1 heart)
	#Range: 0.0 ~ 2048.0
	advancedZombieAttackDamage = 3.0
	#Defines how much damage the zombie deals (2 damage points points = 1 heart)
	#Range: 0.0 ~ 2048.0
	tankZombieAttackDamage = 15.0
	#Defines how much damage the zombie deals (2 damage points points = 1 heart)
	#Range: 0.0 ~ 2048.0
	fastZombieAttackDamage = 1.0
	#Defines how much damage the zombie deals (2 damage points points = 1 heart)
	#Range: 0.0 ~ 2048.0
	weakZombieAttackDamage = 2.0
	#Defines how much damage the zombie deals (2 damage points points = 1 heart)
	#Range: 0.0 ~ 2048.0
	policeZombieAttackDamage = 3.0
	#Defines how much damage the zombie deals (2 damage points points = 1 heart)
	#Range: 0.0 ~ 2048.0
	doctorZombieAttackDamage = 3.0
	#Defines how much damage the zombie deals (2 damage points points = 1 heart)
	#Range: 0.0 ~ 2048.0
	giantZombieAttackDamage = 50.0
	#Defines how fast the zombie moves
	#Range: 0.0 ~ 2048.0
	fastZombieSpeed = 0.33

	#Configure how zombies should spawn
	#Minecraft's spawning is a weighted conditional system
	#With a lower weight, rarer the zombie will be
	#---------------------------------
	#Minimum/Maximum spawn defines how much mobs will be spawned per group
	[zombies.spawning]
		zombiesEnabled = true
		advancedZombiesEnabled = true
		tankZombiesEnabled = true
		fastZombiesEnabled = true
		weakZombiesEnabled = true
		#Range: > 1
		advancedZombieSpawnWeight = 40
		#Range: > 1
		tankZombieSpawnWeight = 5
		#Range: > 1
		fastZombieSpawnWeight = 15
		#Range: > 1
		weakZombieSpawnWeight = 30
		#Range: > 1
		advancedZombieMinSpawn = 2
		#Range: > 1
		tankZombieMinSpawn = 2
		#Range: > 1
		fastZombieMinSpawn = 2
		#Range: > 1
		weakZombieMinSpawn = 2
		#Range: > 1
		advancedZombieMaxSpawn = 8
		#Range: > 1
		tankZombieMaxSpawn = 4
		#Range: > 1
		fastZombieMaxSpawn = 4
		#Range: > 1
		weakZombieMaxSpawn = 12

	[zombies.misc]
		#Spawn chance percentage (1.0 = 100% chance)
		#Range: 0.0 ~ 1.0
		zombieHatSpawnChance = 0.05
		#Spawn chance percentage (1.0 = 100% chance)
		#Range: 0.0 ~ 1.0
		zombieHandSpawnChance = 0.15
		#Spawn chance percentage (1.0 = 100% chance)
		#Range: 0.0 ~ 1.0
		zombieClothingSpawnChance = 0.25
		#Drop chance percentage (drop chance based on vanilla formula, use 2.0 for guarantee drop)
		#Range: 0.0 ~ 2.0
		zombieHatDropChance = 2.0
		#Drop chance percentage (drop chance based on vanilla formula, use 2.0 for guarantee drop)
		#Range: 0.0 ~ 2.0
		zombieHandDropChance = 0.085
		#Drop chance percentage (drop chance based on vanilla formula, use 2.0 for guarantee drop)
		#Range: 0.0 ~ 2.0
		zombieClothingDropChance = 2.0
		#Additional knockback given to all zombies
		#Range: 0.0 ~ 5.0
		zombieAttackKnockback = 0.0

#Allows toggling some gameplay aspects
[abilities]
	#Defines if players can break their legs
	brokenLegsEnabled = true
	#Defines if players can bleed
	bleedingEnabled = true
	#Defines if players can be infected
	infectionEnabled = true

[explosives]
	#Enables the usage of Pipe Bomb
	#It wont prevent the ability to get Pipe Bombs, only the ability to use it
	pipeBombEnabled = true
	#Defines how the explosion should interact with blocks
	#NONE: No block interaction, blocks will remain unchanged
	#BREAK: Blocks are broken, they will be dropped when exploded
	#DESTROY: Blocks are destroyed, nothing will be dropped and only a crater will be left
	#Allowed Values: NONE, BREAK, DESTROY
	pipeBombBlockInteraction = "NONE"
	#The explosion radius (in blocks), it tells how big the explosion should be
	#Range: 0.1 ~ 50.0
	pipeBombRadius = 4.0
	#Defines how strong the explosion knockback should be (Multiplier)
	#Range: 0.0 ~ 30.0
	pipeBombKnockbackMultiplier = 1.0
	#Multiplies the base damage given by the explosion (Multiplier)
	#Range: 0.0 ~ 30.0
	pipeBombDamageMultiplier = 1.0
	#How long before the bomb activates automatically (Ticks)
	#Range: 0 ~ 18000
	pipeBombTicksBeforeActivation = 100

