
[gun]
	#The default fire sound range (block)
	#Range: > 0
	DefaultGunFireSoundDistance = 210
	#The range (block) of other gun sound, reloading sound etc.
	#Range: > 0
	DefaultGunOtherSoundDistance = 210
	#Whether or not the player will consume ammo in creative mode
	CreativePlayerConsumeAmmo = true
	#Auto reload all the guns in player inventory, useful for pvp servers
	AutoReloadWhenRespawn = false

[ammo]
	#Warning: Ammo with explosive properties can set the surroundings on fire
	ExplosiveAmmoFire = false
	#Ammo with explosive properties can add knockback effect
	ExplosiveAmmoKnockBack = true
	#The distance at which the explosion effect can be seen
	#Range: > 0
	ExplosiveAmmoVisibleDistance = 192
	#Those blocks that the ammo can pass through
	PassThroughBlocks = ["minecraft:oak_planks", "minecraft:spruce_planks", "minecraft:birch_planks", "minecraft:jungle_planks", "minecraft:glass", "minecraft:sand", "minecraft:red_sand", "minecraft:acacia_planks", "minecraft:dark_oak_planks", "minecraft:crimson_planks", "minecraft:warped_planks", "minecraft:crimson_stem", "minecraft:warped_stem", "minecraft:stripped_crimson_stem", "minecraft:stripped_warped_stem", "minecraft:gravel", "minecraft:oak_log", "minecraft:stripped_oak_log", "minecraft:oak_wood", "minecraft:spruce_log", "minecraft:spruce_wood", "minecraft:stripped_spruce_log", "minecraft:birch_log", "minecraft:stripped_birch_log", "minecraft:birch_wood", "minecraft:jungle_log", "minecraft:stripped_jungle_log", "minecraft:jungle_wood", "minecraft:acacia_log", "minecraft:stripped_acacia_log", "minecraft:acacia_wood", "minecraft:dark_oak_log", "minecraft:stripped_dark_oak_log", "minecraft:dark_oak_wood", "minecraft:tinted_glass", "minecraft:black_stained_glass", "minecraft:white_stained_glass", "minecraft:orange_stained_glass", "minecraft:magenta_stained_glass", "minecraft:light_blue_stained_glass", "minecraft:yellow_stained_glass", "minecraft:lime_stained_glass", "minecraft:pink_stained_glass", "minecraft:gray_stained_glass", "minecraft:light_gray_stained_glass", "minecraft:cyan_stained_glass", "minecraft:purple_stained_glass", "minecraft:blue_stained_glass", "minecraft:brown_stained_glass", "minecraft:green_stained_glass", "minecraft:red_stained_glass", "minecraft:glass_pane", "minecraft:white_stained_glass_pane", "minecraft:orange_stained_glass_pane", "minecraft:magenta_stained_glass_pane", "minecraft:light_blue_stained_glass_pane", "minecraft:yellow_stained_glass_pane", "minecraft:lime_stained_glass_pane", "minecraft:pink_stained_glass_pane", "minecraft:gray_stained_glass_pane", "minecraft:light_gray_stained_glass_pane", "minecraft:cyan_stained_glass_pane", "minecraft:purple_stained_glass_pane", "minecraft:blue_stained_glass_pane", "minecraft:brown_stained_glass_pane", "minecraft:green_stained_glass_pane", "minecraft:red_stained_glass_pane", "minecraft:black_stained_glass_pane"]
	#Whether a ammo can break the glass
	DestroyGlass = false
	#Whether a ammo can ignite the block
	IgniteBlock = false
	#Whether a ammo can ignite the entity
	IgniteEntity = true
	#Warning: Ammo with explosive properties can break blocks
	ExplosiveAmmoDestroysBlock = true

[other]
	#When enabled, the reload command will not overwrite the default model file under config
	DefaultPackDebug = false
	#The farthest sound distance of the target, including minecarts type
	#Range: > 0
	TargetSoundDistance = 128
	#DEV: Server hitbox offset (If the hitbox is ahead, fill in a negative number)
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	ServerHitboxOffset = 3.0
	#Server hitbox latency fix
	ServerHitboxLatencyFix = true
	#The maximum latency (in milliseconds) for the server hitbox latency fix saved
	#Range: 250.0 ~ 1.7976931348623157E308
	ServerHitboxLatencyMaxSaveMs = 1000.0
	#The gun pack that the client player needs to download, needs to fill in the URL and the SHA1 value of the file
	ClientGunPackDownloadUrls = []

